### ISSUE TITLE
slow training

### ISSUE THREAD

**Issue by ayushv98** [rapidsai-community/rapidsai-csp-utils#48]
Describe the current behavior
after updating the rapid-colab template
it is taking too much time to train. time taken for 1 epoch is 32s
for this new
https://colab.research.google.com/drive/1TAAi_szMfWqRfHVfjGSqnGVLr_ztzUM9?usp=sharing#scrollTo=67T0090Jk2KL

Describe the expected behavior
time taken for 1 epochs is 1s
for this code
please restore shows links for old template
please restore old git without update
please sir i have submit my thesis please restore old code
!git clone https://github.com/rapidsai/rapidsai-csp-utils.git

**Comment by taureandyernv** [comment]
@ayushv98 Let me look into this slowdown in training times.  it shouldn't have impacted that.   Can you elaborate on what is taking longer to train?

I can either provide you with a branch to the old code, which you can switch to easily, or give you a script that only runs that old code.  Just know that you will not be able to run the latest RAPIDS versions beyond 0.19 with it.  Please do join our Slack team RAPIDS GoAI and let me know.

**Comment by taureandyernv** [comment]
Hey @ayushv98 what is your thesis on?  Please do provide us with the model and training information where this slow down is occuring

**Comment by taureandyernv** [comment]
no response from @ayushv98 .  Proposed solution should have sorted him out.  Closing.
