### ISSUE TITLE
rapids-colab-template.ipynb - blazingsql not working correctly on Colab - 23Jun21

### ISSUE THREAD

**Issue by toddkleinhans** [rapidsai-community/rapidsai-csp-utils#50]
Hi!

I followed the steps as indicated in the recent article on 21.06: https://medium.com/rapids-ai/rapids-release-21-06-f9bd2e5a9aa4

Using the new notebook and a Colab Pro subscription, I was able to successfully launch a test using -> import cudf <- YAY!

However, when I tried to run -> from blazingsql import BlazingContext <-, it fails.

Please find attached a screenshot of the error. I am open to help test the issue once the code has been resolved. 

Thanks!

--Todd

![23Jun21_BSQL_error](https://user-images.githubusercontent.com/16514184/123191014-cd849f80-d45d-11eb-86ba-56e58cd07b1f.png)

**Comment by taureandyernv** [comment]
Will PR a fix soon.  Turns out the OS.environ["CONDA_PREFIX"] was not taking when run inside the updated script.  Will change all template files and install instructions
