### ISSUE TITLE
Seaborn not installing with Conda on Rapids  21.08

### ISSUE THREAD

**Issue by alvinjamur** [rapidsai-community/rapidsai-csp-utils#54]
Am using Pop!Os and installed using 

conda create -n rapids-21.08 -c rapidsai -c nvidia -c conda-forge rapids-blazing=21.08 python=3.8 cudatoolkit=11.2

I'm trying to install Seaborn using 

conda install -c anaconda seaborn                   /* supposed to install 0.11.2

BUT...conda does not seem to want to install. Trying for last 15+ minutes. Just seems to be stuck at "examining conflicts"

**Comment by taureandyernv** [comment]
advised using pip. no response so closing.  Please reopen if the problem persists after trying advice! :)
