### ISSUE TITLE
 ModuleNotFoundError: No module named 'BlazingSQL' Error after Installing RAPIDS with 'python rapidsai-csp-utils/colab/install_rapids.py <release> <packages>'

### ISSUE THREAD

**Issue by ssarkar** [rapidsai-community/rapidsai-csp-utils#59]
Hello,
I installed successfully following script on Google Colab:
=============================================
# Installing RAPIDS is now 'python rapidsai-csp-utils/colab/install_rapids.py <release> <packages>'
# The <release> options are 'stable' and 'nightly'.  Leaving it blank or adding any other words will default to stable.
# The <packages> option are default blank or 'core'.  By default, we install RAPIDSAI and BlazingSQL.  The 'core' option will install only RAPIDSAI and not include BlazingSQL, 
!python rapidsai-csp-utils/colab/install_rapids.py stable
import os
os.environ['NUMBAPRO_NVVM'] = '/usr/local/cuda/nvvm/lib64/libnvvm.so'
os.environ['NUMBAPRO_LIBDEVICE'] = '/usr/local/cuda/nvvm/libdevice/'
os.environ['CONDA_PREFIX'] = '/usr/local'
==============================================

But I am getting following Error for BlazingSQL Module:
==========================================
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-88bf0259daa3> in <module>()
----> 1 from BlazingSQL import BlazingContext
      2 import cudf
      3 
      4 bc = BlazingContext()
ModuleNotFoundError: No module named 'BlazingSQL'
============================================

What is missing?  I got same error with "nightly" release.
Thanks,

**Comment by taureandyernv** [comment]
closing.  `Blazingsql` was deprecated and `dask-sql` is the replacement of choice.
