### ISSUE TITLE
No module named pyarrow._cuda

### ISSUE THREAD

**Issue by CedrickArmel** [rapidsai-community/rapidsai-csp-utils#60]
I get this issue while importing cudf or cuml in colab after runned rapids.ai installation steps in the installation notebook.[https://colab.research.google.com/drive/1rY7Ln6rEE1pOlfSHCYOVaqt8OvDO35J0#forceEdit=true&offline=true&sandboxMode=true](url)

**Comment by triper1022** [comment]
the same issue....

**Comment by githendumukiri** [comment]
According to @taureandyernv 

>   https://github.com/rapidsai/cudf/issues/10187. We weren't the only packages affected by it. Today, as Colab doesn't support the latest RAPIDS stable, we recommend transitioning to SageMaker Studio Lab. A notice will go out soon, along with a blog, but if you'd like, please try out the capability here:
 https://github.com/rapidsai-community/rapids-smsl
 You will need a SageMaker Studip Lab account to begin. All that information is in the readme. Hope this helps.

**Comment by taureandyernv** [comment]
I think we fixed this in an update.  closing. thanks for letting us know

**Comment by J0hnArren** [comment]
> I think we fixed this in an update. closing. thanks for letting us know

Has this bug been fixed? How can this issue be solved?
