### ISSUE TITLE
install in colab fails just like issue #75

### ISSUE THREAD

**Issue by jimoreira** [rapidsai-community/rapidsai-csp-utils#78]
I don't mean to write all over again, but the issue is exactly as mentioned in [#75 ](https://github.com/rapidsai-community/rapidsai-csp-utils/issues/75)
Just the difference is that now Colab has python 3.10. 
how can this be solved? 

many thanks.

**Comment by jimoreira** [comment]
trying to downgrade colab python to 3.9 with this [solution](https://stackoverflow.com/questions/68657341/how-can-i-update-google-colabs-python-version). but something didn't work. 
Python 3.9 looks fine, but In this step of the installation `!bash rapidsai-csp-utils/colab/update_gcc.sh
import os
os._exit(00)`  the notebook never reconnects and i lose the changes.

**Comment by taureandyernv** [comment]
thanks for sharing this.  colab updated to python 3.10 and ctk 11.8 so now we can install 23.04 stabled on colab.  the install is a bit longer though...

**Comment by jimoreira** [comment]
great, thanks!
