### ISSUE TITLE
GridsearchCV issue using cuML

### ISSUE THREAD

**Issue by Teezq** [rapidsai-community/rapidsai-csp-utils#80]
Hi, I am trying to perform hyperparameter tuning on cuML instead of the CPU target sklearn package. I have import the package in the same way as follow:

import time
import cuml
from cuml.ensemble import RandomForestClassifier
from cuml.model_selection import GridSearchCV
from cuml.metrics import accuracy_score

start_time = time.time()

# create a random forest classifier object
rfc = RandomForestClassifier()

# set up the parameter grid for hyperparameter tuning
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth': [5, 10, 15, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# set up the GridSearchCV object with cross-validation
grid_search = GridSearchCV(rfc, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1, verbose=1)

# fit the GridSearchCV object on the training data
grid_search.fit(X_train_cudf, Y_train_cudf)

# get the best parameters and the best score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

# create a new random forest classifier object with the best parameters
rfc_best = RandomForestClassifier(**best_params)

# fit the new random forest classifier on the training data
rfc_best.fit(X_train_cudf, Y_train_cudf)

# use the new random forest classifier to make predictions on the test data
Y_pred_cudf = rfc_best.predict(X_test_cudf)

# evaluate the performance of the model using accuracy score
accuracy = accuracy_score(Y_test_cudf, Y_pred_cudf)

# print the best parameters, best score, and accuracy score
print("Best parameters:", best_params)
print("Best score:", best_score)
print("Accuracy score:", accuracy)

end_time = time.time()

elapsed_time = end_time - start_time
elapsed_time_minutes = elapsed_time / 60

print("\nElapsed time:", elapsed_time_minutes, "minutes")

But has gotten the issue: 
TypeError: Implicit conversion to a host NumPy array via __array__ is not allowed, To explicitly construct a GPU matrix, consider using .to_cupy()
To explicitly construct a host matrix, consider using .to_numpy().

Really in need of you guys help on this

**Comment by taureandyernv** [comment]
@Teezq , the best place for this issue is on https://github.com/rapidsai/cuml/issues.  We only handle CSP install issues here.  

I do believe that you have to cast your cudf DF to numpy, as the error explicitly states.  `accuracy = accuracy_score(Y_test_cudf.to_numpy(), Y_pred_cudf)`

you can see it's proper usage in this notebook: https://github.com/rapidsai/cuml/blob/branch-23.12/notebooks/random_forest_demo.ipynb
