### ISSUE TITLE
Unable to import cudf

### ISSUE THREAD

**Issue by ShobyG** [rapidsai-community/rapidsai-csp-utils#86]
!git clone https://github.com/rapidsai/rapidsai-csp-utils.git
!python rapidsai-csp-utils/colab/env-check.py
!python rapidsai-csp-utils/colab/pip-install.py

I have been having trouble installing rapids on Collab since this evening.
Error:
Cloning into 'rapidsai-csp-utils'...
remote: Enumerating objects: 400, done.
remote: Counting objects: 100% (131/131), done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 400 (delta 95), reused 53 (delta 51), pack-reused 269
Receiving objects: 100% (400/400), 109.81 KiB | 6.86 MiB/s, done.
Resolving deltas: 100% (197/197), done.
/content/rapidsai-csp-utils
error: pathspec 'patch-22.12' did not match any file(s) known to git
/content
Collecting pynvml
  Downloading pynvml-11.5.0-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 840.8 kB/s eta 0:00:00
Installing collected packages: pynvml
Successfully installed pynvml-11.5.0
***********************************************************************
Woo! Your instance has the right kind of GPU, a Tesla T4!
We will now install RAPIDS via pip!  Please stand by, should be quick...
***********************************************************************

***********************************************************************
Woo! Your instance has the right kind of GPU, a Tesla T4!
We will now install RAPIDS cuDF, cuML, and cuGraph via pip! 
Please stand by, should be quick...
***********************************************************************

Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com/
Collecting cudf-cu11
  Downloading https://pypi.nvidia.com/cudf-cu11/cudf_cu11-23.12.0-cp310-cp310-manylinux_2_28_x86_64.whl (506.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.4/506.4 MB 3.0 MB/s eta 0:00:00
Collecting cuml-cu11
  Downloading cuml-cu11-23.12.0.tar.gz (6.8 kB)
  Preparing metadata (setup.py): started
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py): finished with status 'error'
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Requirement already satisfied: cupy-cuda11x in /usr/local/lib/python3.10/dist-packages (11.0.0)
Requirement already satisfied: numpy<1.26,>=1.20 in /usr/local/lib/python3.10/dist-packages (from cupy-cuda11x) (1.23.5)
Requirement already satisfied: fastrlock>=0.5 in /usr/local/lib/python3.10/dist-packages (from cupy-cuda11x) (0.8.2)

          ***********************************************************************
          The pip install of RAPIDS is complete.
          
          Please do not run any further installation from the conda based installation methods, as they may cause issues!  
          
          Please ensure that you're pulling from the git repo to remain updated with the latest working install scripts. 
r          
          Troubleshooting:
             - If there is an installation failure, please check back on RAPIDSAI owned templates/notebooks to see how to update your personal files. 
             - If an installation failure persists when using the latest script, please make an issue on https://github.com/rapidsai-community/rapidsai-csp-utils
          ***********************************************************************

**Comment by jparksecurity** [comment]
Meantime, you can use my fix.

My GitHub repo: https://github.com/jparksecurity/rapidsai-csp-utils
My commit: https://github.com/jparksecurity/rapidsai-csp-utils/commit/68591df3edc566722bbae34dabe242473b2c2671

**Comment by ShobyG** [comment]
Thank you!!

**Comment by beckernick** [comment]
The Colab template on https://rapids.ai/#quick-start should now be working as expected
