### ISSUE TITLE
Conda notebook says it's installing via pip

### ISSUE THREAD

**Issue by bdice** [rapidsai-community/rapidsai-csp-utils#90]
The Colab notebook that installs RAPIDS via conda shows a message that it will install with pip, and to "stand by." This is confusing because the cell completes but doesn't install RAPIDS with pip as it says.

https://colab.research.google.com/drive/1TAAi_szMfWqRfHVfjGSqnGVLr_ztzUM9#scrollTo=B0C8IV5TQnjN

https://github.com/rapidsai-community/rapidsai-csp-utils/blob/734c8d09ec90e70812c21c236d9e62865e1197b0/colab/env-check.py#L31

**Comment by taureandyernv** [comment]
thanks @bdice .  i think we fixed this together but didn't close this issue :)
