### ISSUE TITLE
colab conda install notebook isn’t working

### ISSUE THREAD

**Issue by raybellwaves** [rapidsai-community/rapidsai-csp-utils#99]
https://colab.research.google.com/drive/1TAAi_szMfWqRfHVfjGSqnGVLr_ztzUM9 from image attached on https://rapids.ai/
![Screenshot 2024-03-11 at 4 55 53 PM](https://github.com/rapidsai-community/rapidsai-csp-utils/assets/17162724/9fa09f34-07f0-4cb9-9d3d-47bb6acbb23c)

gives

```
/usr/local/lib/python3.10/site-packages/numba/__init__.py in _ensure_critical_deps()
     40         raise ImportError(msg)
     41     elif numpy_version > (1, 24):
---> 42         raise ImportError("Numba needs NumPy 1.24 or less")
     43     try:
     44         import scipy

ImportError: Numba needs NumPy 1.24 or less
```

**Comment by raybellwaves** [comment]
started tinkering here: https://colab.research.google.com/drive/18ai8Q4KBHhZfIDh84WqLT0GFouTtg0WK?usp=sharing
but got `ImportError: /usr/local/lib/python3.10/site-packages/cuml/internals/../../../.././libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12`

**Comment by taureandyernv** [comment]
We're deprecating this Conda install of RAPIDS on Colab.  A bunch has changed under the hood on Colab, including cuDF now being preinstalled.  As cuDF is preinstalled via pip, the conda versions are now very incompatible with Colab (shouldn't have both pip and conda RAPIDS versions, the streams might touch).  You'll start to see assets disappear this week.
